### ISSUE TITLE
[fix] tooltip 아무 글씨 없을 때

### ISSUE THREAD

**Issue by chongin12** [yourssu/YDS-iOS#180]
tooltip 에 아무 글씨가 없을 때 모양이 어색합니다.

|   ![IMG_7006](https://user-images.githubusercontent.com/19565940/200159451-a6298ecc-edf0-4a87-b0dd-314c7067fe96.PNG) | ![IMG_7007](https://user-images.githubusercontent.com/19565940/200159464-5255ddb7-4a5a-419c-b909-f116c81f6356.PNG) |
|:---:|:---:|
| ![IMG_7008](https://user-images.githubusercontent.com/19565940/200159493-2c16a22e-33fa-4ce2-9636-a02a3f9edbc2.PNG) |   |

**Comment by lygon55555** [comment]
@chongin12 
글씨 없을 때의 디자인은 피그마에 없는 거 같은데 디자인팀한테 부탁 안 해도 괜찮을까요??

**Comment by chongin12** [comment]
@lygon55555 
앗 부탁드려야겠네욥
